from training.DataSetUtils import get_pedia_classes

if __name__ == '__main__':
    testdata = get_pedia_classes()
    labels = ['Senator', 'Album', 'Mountain', 'AcademicJournal', 'HistoricBuilding', 'Reptile', 'MilitaryUnit', 'Judge',
              'ChessPlayer', 'TradeUnion', 'Musical', 'Insect', 'Town', 'SupremeCourtOfTheUnitedStatesCase',
              'TennisPlayer', 'SpeedwayRider', 'Publisher', 'GolfPlayer', 'HorseRider', 'ShoppingMall', 'Road',
              'MilitaryPerson', 'Election', 'ArtistDiscography', 'OfficeHolder', 'IceHockeyPlayer', 'Diocese',
              'Library', 'Lake', 'Monarch', 'Conifer', 'Bridge', 'Dam', 'BasketballPlayer', 'Glacier',
              'NationalFootballLeagueSeason', 'RugbyPlayer', 'Single', 'Mayor', 'VoiceActor', 'SoccerManager',
              'Economist', 'Skier', 'HandballPlayer', 'Saint', 'RecordLabel', 'AmateurBoxer', 'HollywoodCartoon',
              'Theatre', 'Legislature', 'ComicsCreator', 'GolfTournament', 'MilitaryConflict', 'CollegeCoach',
              'AnimangaCharacter', 'OlympicEvent', 'Convention', 'University', 'BadmintonPlayer', 'NCAATeamSeason',
              'VideoGame', 'Gymnast', 'Amphibian', 'Band', 'PublicTransitSystem', 'Bird', 'GaelicGamesPlayer',
              'Volcano', 'Hotel', 'Architect', 'MartialArtist', 'BusCompany', 'RadioStation', 'Crustacean', 'Airport',
              'Lighthouse', 'Castle', 'SoccerPlayer', 'BaseballPlayer', 'HorseRace', 'Swimmer', 'Congressman',
              'Stadium', 'Painter', 'MemberOfParliament', 'ChristianBishop', 'CyclingRace', 'RugbyClub', 'HorseTrainer',
              'Engineer', 'Fish', 'Arachnid', 'Prison', 'GrandPrix', 'Fungus', 'MountainRange', 'BroadcastNetwork',
              'PoliticalParty', 'Entomologist', 'Planet', 'AutomobileEngine', 'Moss', 'BaseballSeason', 'Baronet',
              'ArtificialSatellite', 'Manga', 'Play', 'HockeyTeam', 'SoccerTournament', 'SoapCharacter', 'Cycad',
              'Cyclist', 'Medician', 'President', 'School', 'TelevisionStation', 'BasketballTeam', 'Mollusca',
              'BeautyQueen', 'Noble', 'SoccerClubSeason', 'CyclingTeam', 'FootballMatch', 'PrimeMinister',
              'MusicFestival', 'Philosopher', 'RadioHost', 'Hospital', 'RaceHorse', 'Museum', 'Earthquake', 'Poem',
              'Anime', 'RollerCoaster', 'AdultActor', 'Ambassador', 'Bank', 'FigureSkater', 'RailwayLine',
              'FashionDesigner', 'Newspaper', 'Airline', 'Historian', 'MythologicalFigure',
              'EurovisionSongContestEntry', 'WrestlingEvent', 'Journalist', 'Racecourse', 'BasketballLeague',
              'SoccerLeague', 'Religious', 'Village', 'Jockey', 'BusinessPerson', 'MusicGenre', 'HandballTeam',
              'AmericanFootballPlayer', 'BiologicalDatabase', 'Canoeist', 'FormulaOneRacer', 'SumoWrestler',
              'TennisTournament', 'River', 'Grape', 'Skater', 'RugbyLeague', 'ClassicalMusicComposition', 'Fern',
              'NascarDriver', 'Restaurant', 'Cricketer', 'Bodybuilder', 'Chef', 'CultivatedVariety', 'Governor',
              'Cardinal', 'SolarEclipse', 'TableTennisPlayer', 'Model', 'FilmFestival', 'ScreenWriter', 'Brewery',
              'SquashPlayer', 'AustralianRulesFootballPlayer', 'Magazine', 'GolfCourse',
              'WomensTennisAssociationTournament', 'LawFirm', 'Comedian', 'MountainPass', 'Winery', 'GreenAlga',
              'RailwayStation', 'PlayboyPlaymate', 'Galaxy', 'RoadTunnel', 'Rower', 'SportsTeamMember',
              'MixedMartialArtsEvent', 'Photographer', 'CanadianFootballTeam', 'DartsPlayer', 'CricketTeam',
              'ClassicalMusicArtist', 'Cave', 'CricketGround', 'AustralianFootballTeam', 'PokerPlayer', 'Poet',
              'Curler', 'Astronaut', 'BaseballLeague', 'Pope', 'BeachVolleyballPlayer', 'ComicStrip', 'NetballPlayer',
              'IceHockeyLeague', 'Canal', 'LacrossePlayer']

    print(labels.index("Cave"))
